import "./globals.css";
import Providers from "../store/provider";
import GlobalAudio from "../components/globalAudio ";

export const metadata = {
  title: "كي | كارد",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GlobalAudio />
          {children}
        </Providers>
      </body>
    </html>
  );
}
